version: "3"
services:
  regexp-postgres:
    image: postgres:latest
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    container_name: regexp-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5452
    ports:
      - 5452:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=regexpert
    restart: unless-stopped

  app:
    image: reg-exp.jar:latest
    network_mode: regexp_default
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regexp
    expose:
      - 8090
    ports:
      - 8090:8080
    restart: unless-stopped
    depends_on:
      - regexp-postgres
    links:
      - regexp-postgres
volumes:
  postgres-data:
