version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: regexp-postgres
    volumes:
      - $HOME/docker/volumes/regexp:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=regexpert
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: reg-exp.jar:latest
    network_mode: bridge
    container_name: regexp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data:
