server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  mandatory-file-encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: false

  datasource:
#    add POSTGRES_URL variable to docker environment
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/regexpert
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    prefix: file:///${user.dir}/src/main/resources/templates/
    cache: false
    mode: HTML
