server:
  port: 8080


spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  mandatory-file-encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/regexpert
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: beans,health,info,mappings
      base-path: /monitoring
  server:
    port: 9090

jwt:
  header: Authorization
  secret: 'Hkb+5HoNpE34B9xGWF2iZjnWYbvqbQ2H76UR/ePP7x4='
  expiration: 31536000


scheduler:
  cron:
#    guest-reset: "1/5 * * * * ?"
    guest-reset: "0 0/30 * * * ?"
    expire-logout-token-delete: "0 0 0 * * ?"




